///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("06381e37-fb65-414e-a1c1-e97a91fff83e", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRepository repository.
        /// </summary>
        public static TestRepository repo = TestRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://wikipedia.com' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("http://wikipedia.com", "chrome", "", false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WikipediaGoogleChrome.Element585175240' at 572;106.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(1));
            repo.WikipediaGoogleChrome.Element585175240.Click("572;106");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WikipediaGoogleChrome.Element585175240' at 1243;69.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(2));
            repo.WikipediaGoogleChrome.Element585175240.Click("1243;69");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'google' with focus on 'WikipediaGoogleChrome'.", repo.WikipediaGoogleChrome.SelfInfo, new RecordItemIndex(3));
            repo.WikipediaGoogleChrome.Self.PressKeys("google");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WikipediaGoogleChrome.Element585175240' at 1234;74.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(4));
            repo.WikipediaGoogleChrome.Element585175240.Click("1234;74");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'WikipediaGoogleChrome.Element585175240' at 237;121.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(5));
            repo.WikipediaGoogleChrome.Element585175240.DoubleClick("237;121");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'WikipediaGoogleChrome.Element585175240' at 237;121.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(6));
            repo.WikipediaGoogleChrome.Element585175240.DoubleClick("237;121");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'WikipediaGoogleChrome.Element585175240' at 237;121.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(7));
            repo.WikipediaGoogleChrome.Element585175240.DoubleClick("237;121");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WikipediaGoogleChrome.Element585175240' at 287;120.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(8));
            repo.WikipediaGoogleChrome.Element585175240.MoveTo("287;120");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WikipediaGoogleChrome.Element585175240' at 207;115.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(9));
            repo.WikipediaGoogleChrome.Element585175240.MoveTo("207;115");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'WikipediaGoogleChrome.Element585175240'.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(10));
            Validate.Attribute(repo.WikipediaGoogleChrome.Element585175240Info, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WikipediaGoogleChrome.Element585175240'.", repo.WikipediaGoogleChrome.Element585175240Info, new RecordItemIndex(11));
            Validate.Attribute(repo.WikipediaGoogleChrome.Element585175240Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.TestRanorexStudioAdministrator' at 52;11.", repo.Explorer.TestRanorexStudioAdministratorInfo, new RecordItemIndex(12));
            repo.Explorer.TestRanorexStudioAdministrator.Click("52;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
