///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
    [RepositoryFolder("f63fe81a-bfba-4ad2-81c1-a9440ddf1ed9")]
    public partial class TestRepository : RepoGenBaseFolder
    {
        static TestRepository instance = new TestRepository();
        TestRepositoryFolders.WikipediaGoogleChromeAppFolder _wikipediagooglechrome;
        TestRepositoryFolders.ExplorerAppFolder _explorer;
        TestRepositoryFolders.WikipediaAppFolder _wikipedia;
        TestRepositoryFolders.WikipediaTheFreeEncyclopediaAppFolder _wikipediathefreeencyclopedia;
        RepoItemInfo _wikipediathefreeencyclopediagooglInfo;

        /// <summary>
        /// Gets the singleton class instance representing the TestRepository element repository.
        /// </summary>
        [RepositoryFolder("f63fe81a-bfba-4ad2-81c1-a9440ddf1ed9")]
        public static TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRepository() 
            : base("TestRepository", "/", null, 0, false, "f63fe81a-bfba-4ad2-81c1-a9440ddf1ed9", ".\\RepositoryImages\\TestRepositoryf63fe81a.rximgres")
        {
            _wikipediagooglechrome = new TestRepositoryFolders.WikipediaGoogleChromeAppFolder(this);
            _explorer = new TestRepositoryFolders.ExplorerAppFolder(this);
            _wikipedia = new TestRepositoryFolders.WikipediaAppFolder(this);
            _wikipediathefreeencyclopedia = new TestRepositoryFolders.WikipediaTheFreeEncyclopediaAppFolder(this);
            _wikipediathefreeencyclopediagooglInfo = new RepoItemInfo(this, "WikipediaTheFreeEncyclopediaGoogl", "/form[@title~'^Wikipedia,\\ the\\ free\\ encyc']", 30000, null, "9439216c-9c64-41e9-8cb1-e76d446d9cc9");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f63fe81a-bfba-4ad2-81c1-a9440ddf1ed9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WikipediaTheFreeEncyclopediaGoogl item.
        /// </summary>
        [RepositoryItem("9439216c-9c64-41e9-8cb1-e76d446d9cc9")]
        public virtual Ranorex.Form WikipediaTheFreeEncyclopediaGoogl
        {
            get
            {
                 return _wikipediathefreeencyclopediagooglInfo.CreateAdapter<Ranorex.Form>(true);
            }
        }

        /// <summary>
        /// The WikipediaTheFreeEncyclopediaGoogl item info.
        /// </summary>
        [RepositoryItemInfo("9439216c-9c64-41e9-8cb1-e76d446d9cc9")]
        public virtual RepoItemInfo WikipediaTheFreeEncyclopediaGooglInfo
        {
            get
            {
                return _wikipediathefreeencyclopediagooglInfo;
            }
        }

        /// <summary>
        /// The WikipediaGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("2b88dda0-03ac-408d-880a-1c8df3582c35")]
        public virtual TestRepositoryFolders.WikipediaGoogleChromeAppFolder WikipediaGoogleChrome
        {
            get { return _wikipediagooglechrome; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("53683597-4a7a-4af6-a536-f868593a50ed")]
        public virtual TestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Wikipedia folder.
        /// </summary>
        [RepositoryFolder("23d10f1b-529f-4ae4-80e5-807a313facea")]
        public virtual TestRepositoryFolders.WikipediaAppFolder Wikipedia
        {
            get { return _wikipedia; }
        }

        /// <summary>
        /// The WikipediaTheFreeEncyclopedia folder.
        /// </summary>
        [RepositoryFolder("e8aa1721-3c88-473f-9f9b-48699c87bb6d")]
        public virtual TestRepositoryFolders.WikipediaTheFreeEncyclopediaAppFolder WikipediaTheFreeEncyclopedia
        {
            get { return _wikipediathefreeencyclopedia; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.2")]
    public partial class TestRepositoryFolders
    {
        /// <summary>
        /// The WikipediaGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b88dda0-03ac-408d-880a-1c8df3582c35")]
        public partial class WikipediaGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element585175240Info;
            RepoItemInfo _element172300560Info;

            /// <summary>
            /// Creates a new WikipediaGoogleChrome  folder.
            /// </summary>
            public WikipediaGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WikipediaGoogleChrome", "/form[@title='Wikipedia - Google Chrome']", parentFolder, 30000, null, true, "2b88dda0-03ac-408d-880a-1c8df3582c35", "")
            {
                _element585175240Info = new RepoItemInfo(this, "Element585175240", "element[@controlid='585175240']", 30000, null, "b9fe134f-c53c-44fb-9f00-f904bb787827");
                _element172300560Info = new RepoItemInfo(this, "Element172300560", "element[@controlid='172300560']", 30000, null, "6d4b5af3-3422-4fb6-8b10-e834a813312c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b88dda0-03ac-408d-880a-1c8df3582c35")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b88dda0-03ac-408d-880a-1c8df3582c35")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element585175240 item.
            /// </summary>
            [RepositoryItem("b9fe134f-c53c-44fb-9f00-f904bb787827")]
            public virtual Ranorex.Unknown Element585175240
            {
                get
                {
                    return _element585175240Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element585175240 item info.
            /// </summary>
            [RepositoryItemInfo("b9fe134f-c53c-44fb-9f00-f904bb787827")]
            public virtual RepoItemInfo Element585175240Info
            {
                get
                {
                    return _element585175240Info;
                }
            }

            /// <summary>
            /// The Element172300560 item.
            /// </summary>
            [RepositoryItem("6d4b5af3-3422-4fb6-8b10-e834a813312c")]
            public virtual Ranorex.Unknown Element172300560
            {
                get
                {
                    return _element172300560Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element172300560 item info.
            /// </summary>
            [RepositoryItemInfo("6d4b5af3-3422-4fb6-8b10-e834a813312c")]
            public virtual RepoItemInfo Element172300560Info
            {
                get
                {
                    return _element172300560Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("53683597-4a7a-4af6-a536-f868593a50ed")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testranorexstudioadministratorInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "53683597-4a7a-4af6-a536-f868593a50ed", "")
            {
                _testranorexstudioadministratorInfo = new RepoItemInfo(this, "TestRanorexStudioAdministrator", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Test\\ -\\ Ranorex\\ Studio\\ \\(Ad']", 30000, null, "8b8dda85-4a81-4736-91cb-8adeae9386aa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("53683597-4a7a-4af6-a536-f868593a50ed")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("53683597-4a7a-4af6-a536-f868593a50ed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestRanorexStudioAdministrator item.
            /// </summary>
            [RepositoryItem("8b8dda85-4a81-4736-91cb-8adeae9386aa")]
            public virtual Ranorex.Button TestRanorexStudioAdministrator
            {
                get
                {
                    return _testranorexstudioadministratorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TestRanorexStudioAdministrator item info.
            /// </summary>
            [RepositoryItemInfo("8b8dda85-4a81-4736-91cb-8adeae9386aa")]
            public virtual RepoItemInfo TestRanorexStudioAdministratorInfo
            {
                get
                {
                    return _testranorexstudioadministratorInfo;
                }
            }
        }

        /// <summary>
        /// The WikipediaAppFolder folder.
        /// </summary>
        [RepositoryFolder("23d10f1b-529f-4ae4-80e5-807a313facea")]
        public partial class WikipediaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _englishInfo;
            RepoItemInfo _englishwikipediathefreeencyclopediInfo;

            /// <summary>
            /// Creates a new Wikipedia  folder.
            /// </summary>
            public WikipediaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Wikipedia", "/dom[@domain='www.wikipedia.org']", parentFolder, 30000, null, false, "23d10f1b-529f-4ae4-80e5-807a313facea", "")
            {
                _englishInfo = new RepoItemInfo(this, "English", ".//body[#'www-wikipedia-org']/div[1]//strong[@innertext='English']", 30000, null, "33866253-32d5-4848-a972-1043a78b348b");
                _englishwikipediathefreeencyclopediInfo = new RepoItemInfo(this, "EnglishWikipediaTheFreeEncyclopedi", ".//body[#'www-wikipedia-org']//a[@title~'^English\\ —\\ Wikipedia\\ —\\ The']", 30000, null, "1fb34d99-4dfc-4b2b-a783-b160123c290f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("23d10f1b-529f-4ae4-80e5-807a313facea")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("23d10f1b-529f-4ae4-80e5-807a313facea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The English item.
            /// </summary>
            [RepositoryItem("33866253-32d5-4848-a972-1043a78b348b")]
            public virtual Ranorex.StrongTag English
            {
                get
                {
                    return _englishInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The English item info.
            /// </summary>
            [RepositoryItemInfo("33866253-32d5-4848-a972-1043a78b348b")]
            public virtual RepoItemInfo EnglishInfo
            {
                get
                {
                    return _englishInfo;
                }
            }

            /// <summary>
            /// The EnglishWikipediaTheFreeEncyclopedi item.
            /// </summary>
            [RepositoryItem("1fb34d99-4dfc-4b2b-a783-b160123c290f")]
            public virtual Ranorex.ATag EnglishWikipediaTheFreeEncyclopedi
            {
                get
                {
                    return _englishwikipediathefreeencyclopediInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EnglishWikipediaTheFreeEncyclopedi item info.
            /// </summary>
            [RepositoryItemInfo("1fb34d99-4dfc-4b2b-a783-b160123c290f")]
            public virtual RepoItemInfo EnglishWikipediaTheFreeEncyclopediInfo
            {
                get
                {
                    return _englishwikipediathefreeencyclopediInfo;
                }
            }
        }

        /// <summary>
        /// The WikipediaTheFreeEncyclopediaAppFolder folder.
        /// </summary>
        [RepositoryFolder("e8aa1721-3c88-473f-9f9b-48699c87bb6d")]
        public partial class WikipediaTheFreeEncyclopediaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchinputInfo;
            RepoItemInfo _firstheadingInfo;
            RepoItemInfo _logogoogle2013officialsvgInfo;
            RepoItemInfo _guidanceonhowtouseandeditwikipediInfo;
            RepoItemInfo _wikipediafaqInfo;

            /// <summary>
            /// Creates a new WikipediaTheFreeEncyclopedia  folder.
            /// </summary>
            public WikipediaTheFreeEncyclopediaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WikipediaTheFreeEncyclopedia", "/dom[@domain='en.wikipedia.org']", parentFolder, 30000, null, false, "e8aa1721-3c88-473f-9f9b-48699c87bb6d", "")
            {
                _searchinputInfo = new RepoItemInfo(this, "SearchInput", ".//input[#'searchInput']", 30000, null, "ce1ffff2-da0b-4ab9-92b5-b8ec33e75ae7");
                _firstheadingInfo = new RepoItemInfo(this, "FirstHeading", ".//h1[#'firstHeading']", 30000, null, "cd424e2a-3a77-40e6-8422-d13e25f92244");
                _logogoogle2013officialsvgInfo = new RepoItemInfo(this, "LogoGoogle2013OfficialSvg", ".//div[#'mw-content-text']/table[1]/tbody/tr[1]//img[@alt~'^Logo\\ Google\\ 2013\\ Official']", 30000, null, "410eacb1-8579-4c61-a8d8-5762fbef8c54");
                _guidanceonhowtouseandeditwikipediInfo = new RepoItemInfo(this, "GuidanceOnHowToUseAndEditWikipedi", ".//li[#'n-help']/a[@innertext='Help']", 30000, null, "740f0747-bcbe-4a02-90e1-d87f59af4d9b");
                _wikipediafaqInfo = new RepoItemInfo(this, "WikipediaFAQ", ".//div[#'mw-content-text']/table[2]/tbody/tr[5]/td[2]/table[1]//b[@innertext='Search ']/a[@innertext~'^Frequently\\ Asked\\ Question']", 30000, null, "df951c30-df44-4bd8-9b51-e0cf662d8d45");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e8aa1721-3c88-473f-9f9b-48699c87bb6d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e8aa1721-3c88-473f-9f9b-48699c87bb6d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchInput item.
            /// </summary>
            [RepositoryItem("ce1ffff2-da0b-4ab9-92b5-b8ec33e75ae7")]
            public virtual Ranorex.InputTag SearchInput
            {
                get
                {
                    return _searchinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchInput item info.
            /// </summary>
            [RepositoryItemInfo("ce1ffff2-da0b-4ab9-92b5-b8ec33e75ae7")]
            public virtual RepoItemInfo SearchInputInfo
            {
                get
                {
                    return _searchinputInfo;
                }
            }

            /// <summary>
            /// The FirstHeading item.
            /// </summary>
            [RepositoryItem("cd424e2a-3a77-40e6-8422-d13e25f92244")]
            public virtual Ranorex.H1Tag FirstHeading
            {
                get
                {
                    return _firstheadingInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The FirstHeading item info.
            /// </summary>
            [RepositoryItemInfo("cd424e2a-3a77-40e6-8422-d13e25f92244")]
            public virtual RepoItemInfo FirstHeadingInfo
            {
                get
                {
                    return _firstheadingInfo;
                }
            }

            /// <summary>
            /// The LogoGoogle2013OfficialSvg item.
            /// </summary>
            [RepositoryItem("410eacb1-8579-4c61-a8d8-5762fbef8c54")]
            public virtual Ranorex.ImgTag LogoGoogle2013OfficialSvg
            {
                get
                {
                    return _logogoogle2013officialsvgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The LogoGoogle2013OfficialSvg item info.
            /// </summary>
            [RepositoryItemInfo("410eacb1-8579-4c61-a8d8-5762fbef8c54")]
            public virtual RepoItemInfo LogoGoogle2013OfficialSvgInfo
            {
                get
                {
                    return _logogoogle2013officialsvgInfo;
                }
            }

            /// <summary>
            /// The GuidanceOnHowToUseAndEditWikipedi item.
            /// </summary>
            [RepositoryItem("740f0747-bcbe-4a02-90e1-d87f59af4d9b")]
            public virtual Ranorex.ATag GuidanceOnHowToUseAndEditWikipedi
            {
                get
                {
                    return _guidanceonhowtouseandeditwikipediInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GuidanceOnHowToUseAndEditWikipedi item info.
            /// </summary>
            [RepositoryItemInfo("740f0747-bcbe-4a02-90e1-d87f59af4d9b")]
            public virtual RepoItemInfo GuidanceOnHowToUseAndEditWikipediInfo
            {
                get
                {
                    return _guidanceonhowtouseandeditwikipediInfo;
                }
            }

            /// <summary>
            /// The WikipediaFAQ item.
            /// </summary>
            [RepositoryItem("df951c30-df44-4bd8-9b51-e0cf662d8d45")]
            public virtual Ranorex.ATag WikipediaFAQ
            {
                get
                {
                    return _wikipediafaqInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The WikipediaFAQ item info.
            /// </summary>
            [RepositoryItemInfo("df951c30-df44-4bd8-9b51-e0cf662d8d45")]
            public virtual RepoItemInfo WikipediaFAQInfo
            {
                get
                {
                    return _wikipediafaqInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}